export const API_URL = 'http://api.dmt.nomoredomainswork.ru'
export const USER_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjI2NjRhN2Y5MDAzYmY0YzI1YTdkMzYiLCJpYXQiOjE3MTM3OTIyMTUsImV4cCI6MTcxNDM5NzAxNX0.kXWg-ObnYc2qFq4bETAbCRX_o-70oNlpgMv1BrbOwOE'
